2014/01/27 18:47:32 [error] [exception.CException] exception 'CException' with message 'Alias "user.UserModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(196): YiiBase::import('user.UserModule', true)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(282): YiiBase::createComponent('user.UserModule', 'user', NULL, Array)
#2 C:\xampp\htdocs\yii\testdrive\protected\views\layouts\main.php(37): CModule->getModule('user')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#7 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#10 C:\xampp\htdocs\yii\testdrive\protected\views\layouts\column1.php(6): CBaseController->endContent()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\testdrive\protected\controllers\SiteController.php(32): CController->render('index')
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/yii/testdrive/
---
2014/01/27 18:50:48 [error] [exception.CException] exception 'CException' with message 'Alias "user.UserModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(196): YiiBase::import('user.UserModule', true)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(282): YiiBase::createComponent('user.UserModule', 'user', NULL, Array)
#2 C:\xampp\htdocs\yii\testdrive\protected\views\layouts\main.php(37): CModule->getModule('user')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#7 C:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#10 C:\xampp\htdocs\yii\testdrive\protected\views\layouts\column1.php(6): CBaseController->endContent()
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\testdrive\protected\controllers\SiteController.php(32): CController->render('index')
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#20 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#21 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/yii/testdrive/
---
2014/01/27 18:53:22 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.{{users}}' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `{{users}}`.
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\models\UserLogin.php (52)
2014/01/27 18:53:22 [error] [exception.CDbException] exception 'CDbException' with message 'The table "{{users}}" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\yii\testdrive\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\yii\testdrive\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\yii\testdrive\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\xampp\htdocs\yii\testdrive\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/yii/testdrive/index.php/user/login
HTTP_REFERER=http://localhost/yii/testdrive/index.php/user/login
---
2014/01/27 19:05:01 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:07 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:10 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:13 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:17 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:23 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:26 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:30 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/27 19:05:36 [warning] [application] Failed to set unsafe attribute "verifyCode" of "RegistrationForm".
in C:\xampp\htdocs\yii\testdrive\protected\modules\user\controllers\RegistrationController.php (30)
in C:\xampp\htdocs\yii\testdrive\index.php (13)
2014/01/28 18:15:05 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid.
in C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\components\RAuthorizer.php (341)
in C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\models\UserLogin.php (57)
2014/01/28 18:15:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii-unchained\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii-unchained\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\components\RAuthorizer.php(341): CDbAuthManager->getAuthAssignments('1')
#3 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 C:\xampp\htdocs\yii-unchained\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\models\UserLogin.php(57): CWebUser->login(Object(UserIdentity), 0)
#6 C:\xampp\htdocs\yii-unchained\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#7 C:\xampp\htdocs\yii-unchained\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#8 C:\xampp\htdocs\yii-unchained\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#9 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#10 C:\xampp\htdocs\yii-unchained\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#11 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#16 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/user/login
HTTP_REFERER=http://localhost/yii-unchained/testdrive/index.php/user/login
---
2014/01/28 18:15:25 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\components\RInstaller.php (180)
in C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\yii-unchained\testdrive\index.php (13)
2014/01/29 18:45:36 [error] [exception.CException] exception 'CException' with message 'RWebUser and its behaviors do not have a method or closure named "updateSession".' in C:\xampp\htdocs\yii-unchained\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\models\User.php(202): CComponent->__call('updateSession', Array)
#1 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\models\User.php(202): RWebUser->updateSession()
#2 C:\xampp\htdocs\yii-unchained\framework\db\ar\CActiveRecord.php(1126): User->afterSave()
#3 C:\xampp\htdocs\yii-unchained\framework\db\ar\CActiveRecord.php(806): CActiveRecord->update(NULL)
#4 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\controllers\LoginController.php(36): CActiveRecord->save()
#5 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\user\controllers\LoginController.php(20): LoginController->lastViset()
#6 C:\xampp\htdocs\yii-unchained\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#7 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#12 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/user/login
HTTP_REFERER=http://localhost/yii-unchained/testdrive/index.php/user/login
---
2014/01/29 18:46:36 [error] [exception.CException] exception 'CException' with message 'Alias "auditTrail.AuditTrailModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-unchained\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\framework\YiiBase.php(196): YiiBase::import('auditTrail.Audi...', true)
#1 C:\xampp\htdocs\yii-unchained\framework\base\CModule.php(282): YiiBase::createComponent('auditTrail.Audi...', 'auditTrail', NULL, Array)
#2 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(337): CModule->getModule('auditTrail')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(276): CWebApplication->createController('auditTrail')
#4 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#5 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
2014/01/29 18:47:32 [error] [exception.CException] exception 'CException' with message 'Alias "auditTrail.AuditTrailModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-unchained\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\framework\YiiBase.php(196): YiiBase::import('auditTrail.Audi...', true)
#1 C:\xampp\htdocs\yii-unchained\framework\base\CModule.php(282): YiiBase::createComponent('auditTrail.Audi...', 'auditTrail', NULL, Array)
#2 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(337): CModule->getModule('auditTrail')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(276): CWebApplication->createController('auditTrail')
#4 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#5 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
2014/01/29 18:47:34 [error] [exception.CException] exception 'CException' with message 'Alias "auditTrail.AuditTrailModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii-unchained\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\framework\YiiBase.php(196): YiiBase::import('auditTrail.Audi...', true)
#1 C:\xampp\htdocs\yii-unchained\framework\base\CModule.php(282): YiiBase::createComponent('auditTrail.Audi...', 'auditTrail', NULL, Array)
#2 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(337): CModule->getModule('auditTrail')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(276): CWebApplication->createController('auditTrail')
#4 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#5 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
2014/01/29 18:52:19 [error] [exception.CException] exception 'CException' with message 'Property "RWebUser.isAdmin" is not defined.' in C:\xampp\htdocs\yii-unchained\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\framework\web\auth\CWebUser.php(146): CComponent->__get('isAdmin')
#1 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\main.php(41): CWebUser->__get('isAdmin')
#2 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii-unchained\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\auditTrail\controllers\DefaultController.php(7): CController->render('index')
#14 C:\xampp\htdocs\yii-unchained\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#15 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#20 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
2014/01/29 18:55:29 [error] [exception.CException] exception 'CException' with message 'RWebUser and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\yii-unchained\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\main.php(41): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\main.php(41): RWebUser->isAdmin()
#2 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii-unchained\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\auditTrail\controllers\DefaultController.php(7): CController->render('index')
#14 C:\xampp\htdocs\yii-unchained\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#15 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#20 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
2014/01/29 18:55:31 [error] [exception.CException] exception 'CException' with message 'RWebUser and its behaviors do not have a method or closure named "isAdmin".' in C:\xampp\htdocs\yii-unchained\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\main.php(41): CComponent->__call('isAdmin', Array)
#1 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\main.php(41): RWebUser->isAdmin()
#2 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\yii-unchained\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\yii-unchained\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\yii-unchained\testdrive\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\yii-unchained\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii-unchained\testdrive\protected\modules\auditTrail\controllers\DefaultController.php(7): CController->render('index')
#14 C:\xampp\htdocs\yii-unchained\framework\web\actions\CInlineAction.php(49): DefaultController->actionIndex()
#15 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\yii-unchained\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\htdocs\yii-unchained\framework\web\CWebApplication.php(141): CWebApplication->runController('auditTrail')
#20 C:\xampp\htdocs\yii-unchained\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\yii-unchained\testdrive\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii-unchained/testdrive/index.php/auditTrail
---
